# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Adventures in Adelaide
tagline:          'Paiges Adventures in Adelaide!'
description:      'A study abroad travel blog.'
url:              http://adventuresinadelaide.github.io
baseurl:          /

author:
  name:           'Paige Bettge'
  url:            

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/adventuresinadelaide/adventuresinadelaide.github.io
